import { type ExtractedVideo } from '../services/youtubeScraper';
import { type YouTubeMetrics } from '../services/metricsService';
import { type EnrichedVideo } from '../services/videoEnrichmentService';

interface MarkdownDocumentParams {
  video: ExtractedVideo;
  metrics: YouTubeMetrics | null;
  scriptPrompt: string;
  thumbnailPrompt: string;
  enrichedVideo?: Partial<EnrichedVideo> | null;
}

export function generateMarkdownDocument(params: MarkdownDocumentParams): string {
  const { video, metrics, scriptPrompt, thumbnailPrompt, enrichedVideo } = params;
  const timestamp = new Date().toLocaleString();

  const sourceDescription = enrichedVideo?.fullDescription || video.description || 'No description available';
  const hasEnrichment = !!(enrichedVideo?.transcriptSummary || enrichedVideo?.fullDescription || enrichedVideo?.enrichmentSource);
  const enrichmentSource = enrichedVideo?.enrichmentSource || 'none';
  const transcriptPreview = enrichedVideo?.transcriptSummary 
    ? enrichedVideo.transcriptSummary.slice(0, 1200) + (enrichedVideo.transcriptSummary.length > 1200 ? '...' : '')
    : null;

  const markdown = `# 🛑 SYSTEM INSTRUCTIONS FOR AI
You are my expert YouTube production assistant and strategist. This document contains a high-signal replication blueprint generated by Niche Radar Viral Factory.

**CRITICAL WORKFLOW (for best results):**
1. **STEP 1:** Carefully read the entire "Niche Radar Script Replication Blueprint" below. Focus first on the "Accurate Video Extraction", "Viral Hooks & Retention Triggers", and "Viral Score" sections.
2. **STEP 2:** Use the "Structural Template" + "High-Quality Replication Narration Beats" to create your own video. Ground your script in the real patterns and examples from the source while adapting for your voice/niche.
3. **PAUSE** after completing your draft script.
4. **ASK:** End your response with: *"Script blueprint applied. Ready for thumbnail concepts and visual production notes?"*
5. **STEP 3:** Only then proceed to the Thumbnail section and production notes.

Do NOT generate a full video script in one go without following the grounded analysis first.

---

# Niche Radar Viral Factory: Complete Video Analysis & Replication Report

**Generated:** ${timestamp}

**Source Video:** [${video.title}](https://www.youtube.com/watch?v=${video.video_id})

---

## Video Information

| Field | Value |
|-------|-------|
| **Title** | ${video.title} |
| **Video ID** | \`${video.video_id}\` |
| **Channel** | ${video.channel_name} |
| **Upload Date** | ${video.upload_date} |
| **Duration** | ${video.duration} |
| **YouTube URL** | https://www.youtube.com/watch?v=${video.video_id} |

### Description (Source Data)

\`\`\`
${sourceDescription}
\`\`\`

${hasEnrichment ? `### Enrichment Status
- **Sources used:** ${enrichmentSource}
- **Transcript available:** ${transcriptPreview ? 'Yes (partial below)' : 'No (or too short)'}
- **Full description captured:** ${enrichedVideo?.fullDescription ? 'Yes' : 'No'}
` : '### Enrichment Status\n- No external enrichment APIs were used (or keys missing). Description and analysis based on title + basic YouTube data only.\n'}

${transcriptPreview ? `### Transcript Summary (from enrichment)
\`\`\`
${transcriptPreview}
\`\`\`
` : ''}

---

## Analytics Metrics

${
  metrics
    ? `| Metric | Value |
|--------|-------|
| **Total Views** | ${metrics.views.toLocaleString()} |
| **Estimated Gross Revenue** | $${metrics.estimatedRevenue.toFixed(2)} |
| **CPM (Cost Per Mille)** | $${metrics.cpm.toFixed(2)} |
| **Card Click-Through-Rate** | ${(metrics.cardClickThroughRate * 100).toFixed(2)}% |
| **Net RPM (Revenue Per 1K Views)** | $${metrics.netRpm.toFixed(2)} |`
    : 'No metrics data available. Ensure your Google API token is configured.'
}

---

## Niche Radar Script Replication Blueprint (Viral Factory Edition)

The following is a **grounded, high-quality replication asset** produced by analyzing the source video's structure, claims, and proven engagement patterns using real enriched data. It emphasizes accuracy, virality, and actionable strategy.

\`\`\`
${scriptPrompt}
\`\`\`

---

## Thumbnail Prompt for AI Image Generators

### Instructions for Midjourney / Stable Diffusion / Flux

Use the following prompt to generate scroll-stopping thumbnails that match the proven visual language of this high-performing video:

\`\`\`
${thumbnailPrompt}
\`\`\`

---

## How to Use This Report for Maximum Results (Viral Factory Workflow)

1. **Internalize the Accurate Extraction, Viral Hooks & Viral Score** — Understand exactly what made the source video work.
2. **Follow the Structural Template** — Use the beat-by-beat outline as your skeleton.
3. **Adapt the Narration Beats** — Use the provided high-quality samples.
4. **Generate Thumbnails** — Feed the thumbnail section into your image generator.
5. **Produce & Iterate** — Film a test version, analyze retention in YouTube Studio, and refine.
6. **Legal/Ethical Note**: Use this as inspiration and structural guidance. Create original content in your own voice.

---

**Report Generated by Niche Radar Viral Factory** | *YouTube Intelligence Platform*

*All data is provided for educational and strategic planning purposes only. Always create original content.*
`;

  return markdown;
}

export function downloadMarkdownFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || 'niche-radar-analysis.md';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
