import { type ExtractedVideo } from '../services/youtubeScraper';
import { type YouTubeMetrics } from '../services/metricsService';

interface MarkdownDocumentParams {
  video: ExtractedVideo;
  metrics: YouTubeMetrics | null;
  scriptPrompt: string;
  thumbnailPrompt: string;
}

export function generateMarkdownDocument(params: MarkdownDocumentParams): string {
  const { video, metrics, scriptPrompt, thumbnailPrompt } = params;
  const timestamp = new Date().toLocaleString();

  const markdown = `# Niche Radar: Complete Video Analysis Report

**Generated:** ${timestamp}

---

## Video Information

| Field | Value |
|-------|-------|
| **Title** | ${video.title} |
| **Video ID** | \`${video.video_id}\` |
| **Channel** | ${video.channel_name} |
| **Upload Date** | ${video.upload_date} |
| **Duration** | ${video.duration} |
| **YouTube URL** | https://www.youtube.com/watch?v=${video.video_id} |

### Description

\`\`\`
${video.description || 'No description available'}
\`\`\`

---

## Analytics Metrics

${
  metrics
    ? `| Metric | Value |
|--------|-------|
| **Total Views** | ${metrics.views.toLocaleString()} |
| **Estimated Gross Revenue** | $${metrics.estimatedRevenue.toFixed(2)} |
| **CPM (Cost Per Mille)** | $${metrics.cpm.toFixed(2)} |
| **Card Click-Through-Rate** | ${(metrics.cardClickThroughRate * 100).toFixed(2)}% |
| **Net RPM (Revenue Per 1K Views)** | $${metrics.netRpm.toFixed(2)} |`
    : 'No metrics data available. Ensure your Google API token is configured.'
}

---

## Script Replication Prompt

### Instructions for Content Creators

Use the following comprehensive script prompt to create a similar high-performing video:

\`\`\`
${scriptPrompt}
\`\`\`

---

## Thumbnail Prompt for AI Image Generators

### Instructions for Midjourney / Stable Diffusion

Use the following prompt to generate a similar thumbnail design:

\`\`\`
${thumbnailPrompt}
\`\`\`

---

## How to Use This Report

1. **Study the Analytics**: Review the metrics to understand the video's performance characteristics.
2. **Follow the Script Prompt**: Use the script replication prompt to create your own video with similar engagement potential.
3. **Generate a Thumbnail**: Input the thumbnail prompt into Midjourney or Stable Diffusion to create a visually similar thumbnail.
4. **Iterate and Improve**: Customize the prompts based on your unique value proposition and audience.

---

**Report Generated by Niche Radar** | *YouTube Intelligence Platform*

*All data is provided for educational and strategic planning purposes only.*
`;

  return markdown;
}

export function downloadMarkdownFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || 'niche-radar-analysis.md';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
