import { type ExtractedVideo } from '../services/youtubeScraper';
import { type YouTubeMetrics } from '../services/metricsService';

interface MarkdownDocumentParams {
  video: ExtractedVideo;
  metrics: YouTubeMetrics | null;
  scriptPrompt: string;
  thumbnailPrompt: string;
}

export function generateMarkdownDocument(params: MarkdownDocumentParams): string {
  const { video, metrics, scriptPrompt, thumbnailPrompt } = params;
  const timestamp = new Date().toLocaleString();

  const markdown = `# 🛑 SYSTEM INSTRUCTIONS FOR AI
You are my expert YouTube production assistant and strategist. This document contains a high-signal replication blueprint generated by Niche Radar.

**CRITICAL WORKFLOW (for best results):**
1. **STEP 1:** Carefully read the entire "Niche Radar Script Replication Blueprint" below. Focus first on the "Accurate Video Extraction" and "Retention Blueprint Analysis" sections to understand what actually worked.
2. **STEP 2:** Use the "Structural Template" + "High-Quality Replication Narration Beats" to create your own video. Ground your script in the real patterns and examples from the source while adapting for your voice/niche.
3. **PAUSE** after completing your draft script.
4. **ASK:** End your response with: *"Script blueprint applied. Ready for thumbnail concepts and visual production notes?"*
5. **STEP 3:** Only then proceed to the Thumbnail section and production notes.

Do NOT generate a full video script in one go without following the grounded analysis first. Prioritize accuracy and proven patterns over pure invention.

---

# Niche Radar: Complete Video Analysis & Replication Report

**Generated:** ${timestamp}

**Source Video:** [${video.title}](https://www.youtube.com/watch?v=${video.video_id})

---

## Video Information

| Field | Value |
|-------|-------|
| **Title** | ${video.title} |
| **Video ID** | \`${video.video_id}\` |
| **Channel** | ${video.channel_name} |
| **Upload Date** | ${video.upload_date} |
| **Duration** | ${video.duration} |
| **YouTube URL** | https://www.youtube.com/watch?v=${video.video_id} |

### Description (Source Data)

\`\`\`
${video.description || 'No description available'}
\`\`\`

---

## Analytics Metrics

${
  metrics
    ? `| Metric | Value |
|--------|-------|
| **Total Views** | ${metrics.views.toLocaleString()} |
| **Estimated Gross Revenue** | $${metrics.estimatedRevenue.toFixed(2)} |
| **CPM (Cost Per Mille)** | $${metrics.cpm.toFixed(2)} |
| **Card Click-Through-Rate** | ${(metrics.cardClickThroughRate * 100).toFixed(2)}% |
| **Net RPM (Revenue Per 1K Views)** | $${metrics.netRpm.toFixed(2)} |`
    : 'No metrics data available. Ensure your Google API token is configured.'
}

---

## Niche Radar Script Replication Blueprint

The following is a **grounded, high-quality replication asset** produced by analyzing the source video's structure, claims, and proven engagement patterns. It emphasizes accuracy and actionable strategy over hallucinated content.

\`\`\`
${scriptPrompt}
\`\`\`

---

## Thumbnail Prompt for AI Image Generators

### Instructions for Midjourney / Stable Diffusion / Flux

Use the following prompt to generate scroll-stopping thumbnails that match the proven visual language of this high-performing video:

\`\`\`
${thumbnailPrompt}
\`\`\`

---

## How to Use This Report for Maximum Results

1. **Internalize the Accurate Extraction & Blueprint** — Understand exactly what made the source video work before writing.
2. **Follow the Structural Template** — Use the beat-by-beat outline as your skeleton.
3. **Adapt the Narration Beats** — Use the provided high-quality samples as strong starting points, then make them your own.
4. **Generate Thumbnails** — Feed the thumbnail section into your image generator.
5. **Produce & Iterate** — Film a test version, analyze retention in YouTube Studio, and refine.
6. **Legal/Ethical Note**: Use this as inspiration and structural guidance. Create original content in your own voice.

---

**Report Generated by Niche Radar** | *YouTube Intelligence Platform*

*All data is provided for educational and strategic planning purposes only. Always create original content.*
`;

  return markdown;
}

export function downloadMarkdownFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || 'niche-radar-analysis.md';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
